name       : sigil
version    : 0.9.8
release    : 7
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/0.9.8.tar.gz : deee9c43bf51519dbf70c299f0ae396ace7899e416e5d7a39c0b788f83d4d78a
license    : GPL-3.0
summary    : WYSIWYG ePub editor.
component  : office.viewers
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python3)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(zlib)
    - libboost-devel
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-six
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/Update-version.patch
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SKIP_RPATH=1 \
        -DINSTALL_BUNDLED_DICTS=0 \
        -DUSE_SYSTEM_LIBS=1 .
build      : |
    %make
install    : |
    %make_install
