name       : sigil
version    : 1.0.0
release    : 13
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/1.0.0.tar.gz : 431c25791c1bdfa0397a1473aa014727d40b2def7e6be236b23ef98a495b1b10
homepage   : https://sigil-ebook.com/
license    : GPL-3.0-or-later
summary    : Multi-platform EPUB ebook editor
component  : office.viewers
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format (both ePub 2 and ePub 3).
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python3)
    - libboost-devel
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake_ninja  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SKIP_RPATH=1 \
                  -DINSTALL_BUNDLED_DICTS=0 \
                  -DUSE_SYSTEM_LIBS=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
