name       : sigil
version    : 0.9.10
release    : 10
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/0.9.10.tar.gz : 294954c4c2b3f1f9348d4f1bff18edebaba44afae901be3900154778b2f877ed
license    : GPL-3.0-or-later
summary    : WYSIWYG ePub editor
component  : office.viewers
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python3)
    - libboost-devel
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake_ninja  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SKIP_RPATH=1 \
                  -DINSTALL_BUNDLED_DICTS=0 \
                  -DUSE_SYSTEM_LIBS=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
