name       : sigil
version    : 0.9.7
release    : 1
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/0.9.7.tar.gz : 7c42ccc1484a8c4d6d48b6f3fb2904ddcbde9ebbf0853c838b7062175ec77315
license    : GPL-3.0
summary    : WYSIWYG ePub editor.
component  : office
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python-3.5)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(zlib)
    - libboost-devel
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SKIP_RPATH=1 \
        -DINSTALL_BUNDLED_DICTS=0 \
        -DUSE_SYSTEM_LIBS=1 .
build      : |
    %make
install    : |
    %make_install
