name       : sigil
version    : 1.7.0
release    : 22
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/refs/tags/1.7.0.tar.gz : f8ea3c11a33bb54de3de1b401fb7ec8d440a5a63277c4d7ed32a29ba629eac66
homepage   : https://sigil-ebook.com/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Multi-platform EPUB ebook editor
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format (both ePub 2 and ePub 3).
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python3)
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-qtwebengine
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake_ninja  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SKIP_RPATH=1 \
                  -DINSTALL_BUNDLED_DICTS=0 \
                  -DUSE_SYSTEM_LIBS=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
