name       : sigil
version    : 1.4.3
release    : 19
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/1.4.3.tar.gz : 74bd482d3c4fe4b2015ee006a6fa77f1114371bd217e4e7cf1d9a805ea41e719
homepage   : https://sigil-ebook.com/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Multi-platform EPUB ebook editor
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format (both ePub 2 and ePub 3).
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre16)
    - pkgconfig(python3)
    - python-lxml
    - python-six
rundeps    :
    - python-lxml
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake_ninja  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_SKIP_RPATH=1 \
                  -DINSTALL_BUNDLED_DICTS=0 \
                  -DUSE_SYSTEM_LIBS=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
