name       : sigil
version    : 1.9.20
release    : 30
source     :
    - https://github.com/Sigil-Ebook/Sigil/archive/refs/tags/1.9.20.tar.gz : ccba86da91e7d683ef1cbc1140e99f9eec7a802c28951091624285c94337e83d
homepage   : https://sigil-ebook.com/
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Multi-platform EPUB ebook editor
description: |
    Sigil is a free, open source, multi-platform ebook editor. It is designed to edit books in ePub format (both ePub 2 and ePub 3).
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(hunspell)
    - pkgconfig(libpcre2-16)
    - pkgconfig(minizip)
    - pkgconfig(python3)
    - mathjax
    - python-lxml
    - python-six
rundeps    :
    - mathjax
    - python-lxml
    - python-qtwebengine
    - python-six
    - python3-qt5
setup      : |
    sed -i -e 's|\/lib\/|\/lib64\/|' src/CMakeLists.txt
    %cmake_ninja  \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SKIP_RPATH=1 \
        -DDISABLE_UPDATE_CHECK=1 \
        -DINSTALL_BUNDLED_DICTS=0 \
        -DMATHJAX3_DIR=/usr/share/mathjax \
        -DSYSTEM_LIBS_REQUIRED=1 \
        -DUSE_SYSTEM_LIBS=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
